//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuroraDialogEnhancer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("auto")]
        public string App_CurrentCulture {
            get {
                return ((string)(this["App_CurrentCulture"]));
            }
            set {
                this["App_CurrentCulture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string App_CurrentVersion {
            get {
                return ((string)(this["App_CurrentVersion"]));
            }
            set {
                this["App_CurrentVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string App_HookSettings_SelectedGameId {
            get {
                return ((string)(this["App_HookSettings_SelectedGameId"]));
            }
            set {
                this["App_HookSettings_SelectedGameId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool App_IsCloseMinimizes {
            get {
                return ((bool)(this["App_IsCloseMinimizes"]));
            }
            set {
                this["App_IsCloseMinimizes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool App_IsExpertMode {
            get {
                return ((bool)(this["App_IsExpertMode"]));
            }
            set {
                this["App_IsExpertMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool App_IsMinimizeToTaskBar {
            get {
                return ((bool)(this["App_IsMinimizeToTaskBar"]));
            }
            set {
                this["App_IsMinimizeToTaskBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool App_IsScreenshotsManager {
            get {
                return ((bool)(this["App_IsScreenshotsManager"]));
            }
            set {
                this["App_IsScreenshotsManager"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool App_IsScreenshotSound {
            get {
                return ((bool)(this["App_IsScreenshotSound"]));
            }
            set {
                this["App_IsScreenshotSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool App_IsStartup {
            get {
                return ((bool)(this["App_IsStartup"]));
            }
            set {
                this["App_IsStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool App_IsStartMinimized {
            get {
                return ((bool)(this["App_IsStartMinimized"]));
            }
            set {
                this["App_IsStartMinimized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool App_IsUnloadUi {
            get {
                return ((bool)(this["App_IsUnloadUi"]));
            }
            set {
                this["App_IsUnloadUi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("24")]
        public double UI_FontStyle_Title {
            get {
                return ((double)(this["UI_FontStyle_Title"]));
            }
            set {
                this["UI_FontStyle_Title"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public double UI_MainWindow_Width {
            get {
                return ((double)(this["UI_MainWindow_Width"]));
            }
            set {
                this["UI_MainWindow_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("465")]
        public double UI_MainWindow_Height {
            get {
                return ((double)(this["UI_MainWindow_Height"]));
            }
            set {
                this["UI_MainWindow_Height"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double UI_MainWindow_Top {
            get {
                return ((double)(this["UI_MainWindow_Top"]));
            }
            set {
                this["UI_MainWindow_Top"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double UI_MainWindow_Left {
            get {
                return ((double)(this["UI_MainWindow_Left"]));
            }
            set {
                this["UI_MainWindow_Left"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UI_MainWindow_State {
            get {
                return ((int)(this["UI_MainWindow_State"]));
            }
            set {
                this["UI_MainWindow_State"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UI_MainWindow_State_Startup {
            get {
                return ((int)(this["UI_MainWindow_State_Startup"]));
            }
            set {
                this["UI_MainWindow_State_Startup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int UI_MainWindow_State_Shortcut {
            get {
                return ((int)(this["UI_MainWindow_State_Shortcut"]));
            }
            set {
                this["UI_MainWindow_State_Shortcut"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double UI_Scale {
            get {
                return ((double)(this["UI_Scale"]));
            }
            set {
                this["UI_Scale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int UI_InitialPage {
            get {
                return ((int)(this["UI_InitialPage"]));
            }
            set {
                this["UI_InitialPage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UI_ThemeInfo_CustomThemeAccentColor {
            get {
                return ((string)(this["UI_ThemeInfo_CustomThemeAccentColor"]));
            }
            set {
                this["UI_ThemeInfo_CustomThemeAccentColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UI_ThemeInfo_IsCustomAccentColor {
            get {
                return ((bool)(this["UI_ThemeInfo_IsCustomAccentColor"]));
            }
            set {
                this["UI_ThemeInfo_IsCustomAccentColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UI_ThemeInfo_IsSystemApplicationThemeLight {
            get {
                return ((bool)(this["UI_ThemeInfo_IsSystemApplicationThemeLight"]));
            }
            set {
                this["UI_ThemeInfo_IsSystemApplicationThemeLight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UI_ThemeInfo_Location {
            get {
                return ((string)(this["UI_ThemeInfo_Location"]));
            }
            set {
                this["UI_ThemeInfo_Location"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UI_ThemeInfo_SelectedColorType {
            get {
                return ((int)(this["UI_ThemeInfo_SelectedColorType"]));
            }
            set {
                this["UI_ThemeInfo_SelectedColorType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UI_ThemeInfo_ThemeName {
            get {
                return ((string)(this["UI_ThemeInfo_ThemeName"]));
            }
            set {
                this["UI_ThemeInfo_ThemeName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UI_ThemeInfo_Type {
            get {
                return ((int)(this["UI_ThemeInfo_Type"]));
            }
            set {
                this["UI_ThemeInfo_Type"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Update_Frequency {
            get {
                return ((int)(this["Update_Frequency"]));
            }
            set {
                this["Update_Frequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Update_IsUpdateRequired {
            get {
                return ((bool)(this["Update_IsUpdateRequired"]));
            }
            set {
                this["Update_IsUpdateRequired"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime Update_LastUpdateCheckTime {
            get {
                return ((global::System.DateTime)(this["Update_LastUpdateCheckTime"]));
            }
            set {
                this["Update_LastUpdateCheckTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Update_UpdateServerUri {
            get {
                return ((string)(this["Update_UpdateServerUri"]));
            }
            set {
                this["Update_UpdateServerUri"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string WebClient_UserAgent {
            get {
                return ((string)(this["WebClient_UserAgent"]));
            }
            set {
                this["WebClient_UserAgent"] = value;
            }
        }
    }
}
