//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuroraDialogEnhancer.Properties.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AuroraDialogEnhancer.Properties.Localization.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Thanks.
        /// </summary>
        public static string About_Acknowledgements {
            get {
                return ResourceManager.GetString("About_Acknowledgements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All of you, friends.
        /// </summary>
        public static string About_AllOfYou {
            get {
                return ResourceManager.GetString("About_AllOfYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application icon.
        /// </summary>
        public static string About_ApplicationIcon {
            get {
                return ResourceManager.GetString("About_ApplicationIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to consultant.
        /// </summary>
        public static string About_Consultant {
            get {
                return ResourceManager.GetString("About_Consultant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kind international project.
        /// </summary>
        public static string About_CreativeSociety_Description_1 {
            get {
                return ResourceManager.GetString("About_CreativeSociety_Description_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Human Life is the Highest Value.
        /// </summary>
        public static string About_CreativeSociety_Description_2 {
            get {
                return ResourceManager.GetString("About_CreativeSociety_Description_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://creativesociety.com.
        /// </summary>
        public static string About_CreativeSociety_Link {
            get {
                return ResourceManager.GetString("About_CreativeSociety_Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creative Society.
        /// </summary>
        public static string About_CreativeSociety_Title {
            get {
                return ResourceManager.GetString("About_CreativeSociety_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lead developer.
        /// </summary>
        public static string About_LeadDeveloper {
            get {
                return ResourceManager.GetString("About_LeadDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Libraries and Resources.
        /// </summary>
        public static string About_LibrariesAndResources {
            get {
                return ResourceManager.GetString("About_LibrariesAndResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified versions.
        /// </summary>
        public static string About_ModifiedVersion {
            get {
                return ResourceManager.GetString("About_ModifiedVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-release.
        /// </summary>
        public static string About_PreRelease {
            get {
                return ResourceManager.GetString("About_PreRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special thanks.
        /// </summary>
        public static string About_SpecialThanks {
            get {
                return ResourceManager.GetString("About_SpecialThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tester.
        /// </summary>
        public static string About_Tester {
            get {
                return ResourceManager.GetString("About_Tester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you, thank you, thank you!.
        /// </summary>
        public static string About_ThankYou {
            get {
                return ResourceManager.GetString("About_ThankYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dutch translation.
        /// </summary>
        public static string About_Translation_Dutch {
            get {
                return ResourceManager.GetString("About_Translation_Dutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English translation.
        /// </summary>
        public static string About_Translation_English {
            get {
                return ResourceManager.GetString("About_Translation_English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to German translation.
        /// </summary>
        public static string About_Translation_German {
            get {
                return ResourceManager.GetString("About_Translation_German", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ukranian translation.
        /// </summary>
        public static string About_Translation_Ukranian {
            get {
                return ResourceManager.GetString("About_Translation_Ukranian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every two weeks.
        /// </summary>
        public static string About_Update_Frequency_EveryTwoWeeks {
            get {
                return ResourceManager.GetString("About_Update_Frequency_EveryTwoWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every month.
        /// </summary>
        public static string About_Update_Frequency_Monthly {
            get {
                return ResourceManager.GetString("About_Update_Frequency_Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t check.
        /// </summary>
        public static string About_Update_Frequency_None {
            get {
                return ResourceManager.GetString("About_Update_Frequency_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates check frequency.
        /// </summary>
        public static string About_Update_Frequency_ToolTip {
            get {
                return ResourceManager.GetString("About_Update_Frequency_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once a week.
        /// </summary>
        public static string About_Update_Frequency_Weekly {
            get {
                return ResourceManager.GetString("About_Update_Frequency_Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string About_Update_Update_Verb {
            get {
                return ResourceManager.GetString("About_Update_Update_Verb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User interface.
        /// </summary>
        public static string About_UserInterface {
            get {
                return ResourceManager.GetString("About_UserInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string About_Version {
            get {
                return ResourceManager.GetString("About_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version info.
        /// </summary>
        public static string About_VersionInfo {
            get {
                return ResourceManager.GetString("About_VersionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the application accent color.
        /// </summary>
        public static string Appearance_AccentColor_Description {
            get {
                return ResourceManager.GetString("Appearance_AccentColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore default.
        /// </summary>
        public static string Appearance_AccentColor_RestoreDefault {
            get {
                return ResourceManager.GetString("Appearance_AccentColor_RestoreDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent color.
        /// </summary>
        public static string Appearance_AccentColor_Title {
            get {
                return ResourceManager.GetString("Appearance_AccentColor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Appearance_ColorTheme_Create {
            get {
                return ResourceManager.GetString("Appearance_ColorTheme_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Appearance_ColorTheme_Custom {
            get {
                return ResourceManager.GetString("Appearance_ColorTheme_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Appearance_ColorTheme_Dark {
            get {
                return ResourceManager.GetString("Appearance_ColorTheme_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default application color scheme.
        /// </summary>
        public static string Appearance_ColorTheme_Description {
            get {
                return ResourceManager.GetString("Appearance_ColorTheme_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Appearance_ColorTheme_Export {
            get {
                return ResourceManager.GetString("Appearance_ColorTheme_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Appearance_ColorTheme_Import {
            get {
                return ResourceManager.GetString("Appearance_ColorTheme_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Appearance_ColorTheme_Light {
            get {
                return ResourceManager.GetString("Appearance_ColorTheme_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme management.
        /// </summary>
        public static string Appearance_ColorTheme_Management {
            get {
                return ResourceManager.GetString("Appearance_ColorTheme_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string Appearance_ColorTheme_System {
            get {
                return ResourceManager.GetString("Appearance_ColorTheme_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base color scheme.
        /// </summary>
        public static string Appearance_ColorTheme_Title {
            get {
                return ResourceManager.GetString("Appearance_ColorTheme_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Appearance_Cursor_Default {
            get {
                return ResourceManager.GetString("Appearance_Cursor_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hand.
        /// </summary>
        public static string Appearance_Cursor_Hand {
            get {
                return ResourceManager.GetString("Appearance_Cursor_Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction cursor.
        /// </summary>
        public static string Appearance_Cursor_Title {
            get {
                return ResourceManager.GetString("Appearance_Cursor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme export error.
        /// </summary>
        public static string Appearance_Error_Export {
            get {
                return ResourceManager.GetString("Appearance_Error_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme import error.
        /// </summary>
        public static string Appearance_Error_Import {
            get {
                return ResourceManager.GetString("Appearance_Error_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application interface font.
        /// </summary>
        public static string Appearance_Font_Title {
            get {
                return ResourceManager.GetString("Appearance_Font_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Appearance_Title {
            get {
                return ResourceManager.GetString("Appearance_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore default.
        /// </summary>
        public static string Appearance_ZoomLevel_RestoreDefault {
            get {
                return ResourceManager.GetString("Appearance_ZoomLevel_RestoreDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom level.
        /// </summary>
        public static string Appearance_ZoomLevel_Title {
            get {
                return ResourceManager.GetString("Appearance_ZoomLevel_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string AutoUpdate_Cancel {
            get {
                return ResourceManager.GetString("AutoUpdate_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changelog.
        /// </summary>
        public static string AutoUpdate_Changelog {
            get {
                return ResourceManager.GetString("AutoUpdate_Changelog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string AutoUpdate_Close {
            get {
                return ResourceManager.GetString("AutoUpdate_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have the latest version: {0}.
        /// </summary>
        public static string AutoUpdate_CurrentIsLatestVersion {
            get {
                return ResourceManager.GetString("AutoUpdate_CurrentIsLatestVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current version: {0}.
        /// </summary>
        public static string AutoUpdate_CurrentVersion {
            get {
                return ResourceManager.GetString("AutoUpdate_CurrentVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download speed.
        /// </summary>
        public static string AutoUpdate_DownloadSpeed {
            get {
                return ResourceManager.GetString("AutoUpdate_DownloadSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sec.
        /// </summary>
        public static string AutoUpdate_DownloadSpeed_Seconds {
            get {
                return ResourceManager.GetString("AutoUpdate_DownloadSpeed_Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem reaching update server. Please check your internet connection and try again later..
        /// </summary>
        public static string AutoUpdate_Failed_Message {
            get {
                return ResourceManager.GetString("AutoUpdate_Failed_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Check Failed.
        /// </summary>
        public static string AutoUpdate_Failed_Title {
            get {
                return ResourceManager.GetString("AutoUpdate_Failed_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version available: {0}.
        /// </summary>
        public static string AutoUpdate_NewVersionAvailable {
            get {
                return ResourceManager.GetString("AutoUpdate_NewVersionAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to determine the filename of the update file!.
        /// </summary>
        public static string AutoUpdate_UnableToDetermineFileName {
            get {
                return ResourceManager.GetString("AutoUpdate_UnableToDetermineFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem reaching update server. Please check your internet connection and try again later..
        /// </summary>
        public static string AutoUpdate_Unavailable_Message {
            get {
                return ResourceManager.GetString("AutoUpdate_Unavailable_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Unavailable.
        /// </summary>
        public static string AutoUpdate_Unavailable_Title {
            get {
                return ResourceManager.GetString("AutoUpdate_Unavailable_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string AutoUpdate_Update_Verb {
            get {
                return ResourceManager.GetString("AutoUpdate_Update_Verb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string AutoUpdate_WindowTitle {
            get {
                return ResourceManager.GetString("AutoUpdate_WindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading an update.
        /// </summary>
        public static string AutoUpdate_WindowTitle_Download {
            get {
                return ResourceManager.GetString("AutoUpdate_WindowTitle_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string ColorPickerDialog_Apply {
            get {
                return ResourceManager.GetString("ColorPickerDialog_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string ColorPickerDialog_Cancel {
            get {
                return ResourceManager.GetString("ColorPickerDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accent color picker.
        /// </summary>
        public static string ColorPickerDialog_Title {
            get {
                return ResourceManager.GetString("ColorPickerDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimized.
        /// </summary>
        public static string CoreInfoState_ClientSize_Minimized {
            get {
                return ResourceManager.GetString("CoreInfoState_ClientSize_Minimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceling....
        /// </summary>
        public static string CoreInfoState_Detection_Canceled {
            get {
                return ResourceManager.GetString("CoreInfoState_Detection_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string CoreInfoState_Detection_Detected {
            get {
                return ResourceManager.GetString("CoreInfoState_Detection_Detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string CoreInfoState_Detection_Search {
            get {
                return ResourceManager.GetString("CoreInfoState_Detection_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string CoreInfoState_DialogMode_No {
            get {
                return ResourceManager.GetString("CoreInfoState_DialogMode_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string CoreInfoState_DialogMode_Yes {
            get {
                return ResourceManager.GetString("CoreInfoState_DialogMode_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File reading error.
        /// </summary>
        public static string EntityRepository_Error_Read {
            get {
                return ResourceManager.GetString("EntityRepository_Error_Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File writing error.
        /// </summary>
        public static string EntityRepository_Error_Write {
            get {
                return ResourceManager.GetString("EntityRepository_Error_Write", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files.
        /// </summary>
        public static string FileDialog_AllFiles {
            get {
                return ResourceManager.GetString("FileDialog_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        public static string FileDialog_File {
            get {
                return ResourceManager.GetString("FileDialog_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files.
        /// </summary>
        public static string FileDialog_Files {
            get {
                return ResourceManager.GetString("FileDialog_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save profile shortcut.
        /// </summary>
        public static string FileDialog_Shortcut_Title {
            get {
                return ResourceManager.GetString("FileDialog_Shortcut_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string FontPicker_Apply {
            get {
                return ResourceManager.GetString("FontPicker_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string FontPicker_Cancel {
            get {
                return ResourceManager.GetString("FontPicker_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string FontPicker_FontSize {
            get {
                return ResourceManager.GetString("FontPicker_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font picker.
        /// </summary>
        public static string FontPicker_Title {
            get {
                return ResourceManager.GetString("FontPicker_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional settings.
        /// </summary>
        public static string HookSettings_AdditionalSettings {
            get {
                return ResourceManager.GetString("HookSettings_AdditionalSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create launch shortcut for this profile.
        /// </summary>
        public static string HookSettings_CreateShortcut_Description {
            get {
                return ResourceManager.GetString("HookSettings_CreateShortcut_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create shortcut.
        /// </summary>
        public static string HookSettings_CreateShortcut_Title {
            get {
                return ResourceManager.GetString("HookSettings_CreateShortcut_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game location is not specified.
        /// </summary>
        public static string HookSettings_Error_Location_Game_Empty {
            get {
                return ResourceManager.GetString("HookSettings_Error_Location_Game_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game location does not exist.
        /// </summary>
        public static string HookSettings_Error_Location_Game_NotExists {
            get {
                return ResourceManager.GetString("HookSettings_Error_Location_Game_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher location is not specified.
        /// </summary>
        public static string HookSettings_Error_Location_Launcher_Empty {
            get {
                return ResourceManager.GetString("HookSettings_Error_Location_Launcher_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher location does not exist.
        /// </summary>
        public static string HookSettings_Error_Location_Launcher_NotExists {
            get {
                return ResourceManager.GetString("HookSettings_Error_Location_Launcher_NotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is missing.
        /// </summary>
        public static string HookSettings_Error_Preset_IsMissing {
            get {
                return ResourceManager.GetString("HookSettings_Error_Preset_IsMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset resolution.
        /// </summary>
        public static string HookSettings_Error_Preset_Preset {
            get {
                return ResourceManager.GetString("HookSettings_Error_Preset_Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image template for resolution.
        /// </summary>
        public static string HookSettings_Error_Preset_TemplateImage {
            get {
                return ResourceManager.GetString("HookSettings_Error_Preset_TemplateImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game process name is not specified.
        /// </summary>
        public static string HookSettings_Error_ProcessName_Game {
            get {
                return ResourceManager.GetString("HookSettings_Error_ProcessName_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher process name is not specified.
        /// </summary>
        public static string HookSettings_Error_ProcessName_Launcher {
            get {
                return ResourceManager.GetString("HookSettings_Error_ProcessName_Launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close application on game exit.
        /// </summary>
        public static string HookSettings_ExitSettings_Description {
            get {
                return ResourceManager.GetString("HookSettings_ExitSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit with the game.
        /// </summary>
        public static string HookSettings_ExitSettings_Title {
            get {
                return ResourceManager.GetString("HookSettings_ExitSettings_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hook info.
        /// </summary>
        public static string HookSettings_HookInfo {
            get {
                return ResourceManager.GetString("HookSettings_HookInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hook settings.
        /// </summary>
        public static string HookSettings_HookSettings {
            get {
                return ResourceManager.GetString("HookSettings_HookSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game location.
        /// </summary>
        public static string HookSettings_Location_Game {
            get {
                return ResourceManager.GetString("HookSettings_Location_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher location.
        /// </summary>
        public static string HookSettings_Location_Launcher {
            get {
                return ResourceManager.GetString("HookSettings_Location_Launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshots folder location.
        /// </summary>
        public static string HookSettings_Location_Screenshots {
            get {
                return ResourceManager.GetString("HookSettings_Location_Screenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch at hook start.
        /// </summary>
        public static string HookSettings_OnLaunch_Action {
            get {
                return ResourceManager.GetString("HookSettings_OnLaunch_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game.
        /// </summary>
        public static string HookSettings_OnLaunch_Type_Game {
            get {
                return ResourceManager.GetString("HookSettings_OnLaunch_Type_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher.
        /// </summary>
        public static string HookSettings_OnLaunch_Type_Launcher {
            get {
                return ResourceManager.GetString("HookSettings_OnLaunch_Type_Launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        public static string HookSettings_OnLaunch_Type_Nothing {
            get {
                return ResourceManager.GetString("HookSettings_OnLaunch_Type_Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open screenshots folder.
        /// </summary>
        public static string HookSettings_OpenScreenShotsFolder {
            get {
                return ResourceManager.GetString("HookSettings_OpenScreenShotsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game process name.
        /// </summary>
        public static string HookSettings_ProcessName_Game {
            get {
                return ResourceManager.GetString("HookSettings_ProcessName_Game", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launcher process name.
        /// </summary>
        public static string HookSettings_ProcessName_Launcher {
            get {
                return ResourceManager.GetString("HookSettings_ProcessName_Launcher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string HookSettings_Profile {
            get {
                return ResourceManager.GetString("HookSettings_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locate.
        /// </summary>
        public static string HookSettings_Settings_Action_Locate {
            get {
                return ResourceManager.GetString("HookSettings_Settings_Action_Locate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string HookSettings_Settings_Action_Reset {
            get {
                return ResourceManager.GetString("HookSettings_Settings_Action_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string HookSettings_State_AppException {
            get {
                return ResourceManager.GetString("HookSettings_State_AppException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelling.
        /// </summary>
        public static string HookSettings_State_Canceled {
            get {
                return ResourceManager.GetString("HookSettings_State_Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detected.
        /// </summary>
        public static string HookSettings_State_Detected {
            get {
                return ResourceManager.GetString("HookSettings_State_Detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string HookSettings_State_Error {
            get {
                return ResourceManager.GetString("HookSettings_State_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string HookSettings_State_None {
            get {
                return ResourceManager.GetString("HookSettings_State_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string HookSettings_State_Paused {
            get {
                return ResourceManager.GetString("HookSettings_State_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching.
        /// </summary>
        public static string HookSettings_State_Search {
            get {
                return ResourceManager.GetString("HookSettings_State_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to stop the search.
        /// </summary>
        public static string HookSettings_State_Search_PressToStop {
            get {
                return ResourceManager.GetString("HookSettings_State_Search_PressToStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string HookSettings_State_Warning {
            get {
                return ResourceManager.GetString("HookSettings_State_Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The changes will be applied after restarting the hook.
        /// </summary>
        public static string HookSettings_Warning_UnappliedChanges {
            get {
                return ResourceManager.GetString("HookSettings_Warning_UnappliedChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string InfoDialog_Cancel {
            get {
                return ResourceManager.GetString("InfoDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string InfoDialog_Error {
            get {
                return ResourceManager.GetString("InfoDialog_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string InfoDialog_Info {
            get {
                return ResourceManager.GetString("InfoDialog_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string InfoDialog_Ok {
            get {
                return ResourceManager.GetString("InfoDialog_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong.
        /// </summary>
        public static string InfoDialog_SomethingWentWrong {
            get {
                return ResourceManager.GetString("InfoDialog_SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog option.
        /// </summary>
        public static string KeyBindAction_DialogOption {
            get {
                return ResourceManager.GetString("KeyBindAction_DialogOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual dialog mode.
        /// </summary>
        public static string KeyBindAction_ManualDialogMode {
            get {
                return ResourceManager.GetString("KeyBindAction_ManualDialogMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string KeyBindAction_Next {
            get {
                return ResourceManager.GetString("KeyBindAction_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string KeyBindAction_Previous {
            get {
                return ResourceManager.GetString("KeyBindAction_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot.
        /// </summary>
        public static string KeyBindAction_ScreenShot {
            get {
                return ResourceManager.GetString("KeyBindAction_ScreenShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string KeyBindAction_Select {
            get {
                return ResourceManager.GetString("KeyBindAction_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string KeyBinding_AutoSkip_Action {
            get {
                return ResourceManager.GetString("KeyBinding_AutoSkip_Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Config.
        /// </summary>
        public static string KeyBinding_AutoSkip_Config {
            get {
                return ResourceManager.GetString("KeyBinding_AutoSkip_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        public static string KeyBinding_AutoSkip_Delay_Milliseconds {
            get {
                return ResourceManager.GetString("KeyBinding_AutoSkip_Delay_Milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click delay.
        /// </summary>
        public static string KeyBinding_AutoSkip_Delay_Title {
            get {
                return ResourceManager.GetString("KeyBinding_AutoSkip_Delay_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To skip typewriting effect.
        /// </summary>
        public static string KeyBinding_AutoSkip_DoubleClickDelay_Description {
            get {
                return ResourceManager.GetString("KeyBinding_AutoSkip_DoubleClickDelay_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click delay.
        /// </summary>
        public static string KeyBinding_AutoSkip_DoubleClickDelay_Title {
            get {
                return ResourceManager.GetString("KeyBinding_AutoSkip_DoubleClickDelay_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text and replies.
        /// </summary>
        public static string KeyBinding_AutoSkip_Mode_Everything {
            get {
                return ResourceManager.GetString("KeyBinding_AutoSkip_Mode_Everything", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text only.
        /// </summary>
        public static string KeyBinding_AutoSkip_Mode_Text {
            get {
                return ResourceManager.GetString("KeyBinding_AutoSkip_Mode_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip mode.
        /// </summary>
        public static string KeyBinding_AutoSkip_Mode_Title {
            get {
                return ResourceManager.GetString("KeyBinding_AutoSkip_Mode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursor presence.
        /// </summary>
        public static string KeyBinding_AutoSkip_SkipStartCondition_Cursor {
            get {
                return ResourceManager.GetString("KeyBinding_AutoSkip_SkipStartCondition_Cursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speaker name presence.
        /// </summary>
        public static string KeyBinding_AutoSkip_SkipStartCondition_Speaker {
            get {
                return ResourceManager.GetString("KeyBinding_AutoSkip_SkipStartCondition_Speaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start condition.
        /// </summary>
        public static string KeyBinding_AutoSkip_SkipStartCondition_Title {
            get {
                return ResourceManager.GetString("KeyBinding_AutoSkip_SkipStartCondition_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Controls.
        /// </summary>
        public static string KeyBinding_Control {
            get {
                return ResourceManager.GetString("KeyBinding_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoplay.
        /// </summary>
        public static string KeyBinding_Control_AutoDialog {
            get {
                return ResourceManager.GetString("KeyBinding_Control_AutoDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoskip.
        /// </summary>
        public static string KeyBinding_Control_AutoSkip {
            get {
                return ResourceManager.GetString("KeyBinding_Control_AutoSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fullscreen pop-up click.
        /// </summary>
        public static string KeyBinding_Control_FullScreenPopUpMouseClick {
            get {
                return ResourceManager.GetString("KeyBinding_Control_FullScreenPopUpMouseClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide UI.
        /// </summary>
        public static string KeyBinding_Control_HideUi {
            get {
                return ResourceManager.GetString("KeyBinding_Control_HideUi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string KeyBinding_Control_Next {
            get {
                return ResourceManager.GetString("KeyBinding_Control_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string KeyBinding_Control_Previous {
            get {
                return ResourceManager.GetString("KeyBinding_Control_Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string KeyBinding_Control_Select {
            get {
                return ResourceManager.GetString("KeyBinding_Control_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string KeyBinding_General {
            get {
                return ResourceManager.GetString("KeyBinding_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide cursor.
        /// </summary>
        public static string KeyBinding_General_HideCursor {
            get {
                return ResourceManager.GetString("KeyBinding_General_HideCursor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause/Resume hook.
        /// </summary>
        public static string KeyBinding_General_PauseResume {
            get {
                return ResourceManager.GetString("KeyBinding_General_PauseResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload hook.
        /// </summary>
        public static string KeyBinding_General_Reload {
            get {
                return ResourceManager.GetString("KeyBinding_General_Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot.
        /// </summary>
        public static string KeyBinding_General_Screenshot {
            get {
                return ResourceManager.GetString("KeyBinding_General_Screenshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dialog option selection.
        /// </summary>
        public static string KeyBinding_Numeric {
            get {
                return ResourceManager.GetString("KeyBinding_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eighth.
        /// </summary>
        public static string KeyBinding_Numeric_Eighth {
            get {
                return ResourceManager.GetString("KeyBinding_Numeric_Eighth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fifth.
        /// </summary>
        public static string KeyBinding_Numeric_Fifth {
            get {
                return ResourceManager.GetString("KeyBinding_Numeric_Fifth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string KeyBinding_Numeric_First {
            get {
                return ResourceManager.GetString("KeyBinding_Numeric_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourth.
        /// </summary>
        public static string KeyBinding_Numeric_Fourth {
            get {
                return ResourceManager.GetString("KeyBinding_Numeric_Fourth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ninth.
        /// </summary>
        public static string KeyBinding_Numeric_Ninth {
            get {
                return ResourceManager.GetString("KeyBinding_Numeric_Ninth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        public static string KeyBinding_Numeric_Second {
            get {
                return ResourceManager.GetString("KeyBinding_Numeric_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seventh.
        /// </summary>
        public static string KeyBinding_Numeric_Seventh {
            get {
                return ResourceManager.GetString("KeyBinding_Numeric_Seventh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sixth.
        /// </summary>
        public static string KeyBinding_Numeric_Sixth {
            get {
                return ResourceManager.GetString("KeyBinding_Numeric_Sixth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tenth.
        /// </summary>
        public static string KeyBinding_Numeric_Tenth {
            get {
                return ResourceManager.GetString("KeyBinding_Numeric_Tenth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third.
        /// </summary>
        public static string KeyBinding_Numeric_Third {
            get {
                return ResourceManager.GetString("KeyBinding_Numeric_Third", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string KeyBinding_Profile {
            get {
                return ResourceManager.GetString("KeyBinding_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripts.
        /// </summary>
        public static string KeyBinding_Scripts {
            get {
                return ResourceManager.GetString("KeyBinding_Scripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string KeyBinding_Settings_Action_Clear {
            get {
                return ResourceManager.GetString("KeyBinding_Settings_Action_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string KeyBinding_Settings_Action_Reset {
            get {
                return ResourceManager.GetString("KeyBinding_Settings_Action_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        public static string KeyBinding_Utilities {
            get {
                return ResourceManager.GetString("KeyBinding_Utilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cursor behavior.
        /// </summary>
        public static string KeyBinding_Utilities_CursorBehaviour {
            get {
                return ResourceManager.GetString("KeyBinding_Utilities_CursorBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        public static string KeyBinding_Utilities_CursorBehaviour_Hide {
            get {
                return ResourceManager.GetString("KeyBinding_Utilities_CursorBehaviour_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide after selection.
        /// </summary>
        public static string KeyBinding_Utilities_CursorBehaviour_HideAfterSelection {
            get {
                return ResourceManager.GetString("KeyBinding_Utilities_CursorBehaviour_HideAfterSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing.
        /// </summary>
        public static string KeyBinding_Utilities_CursorBehaviour_Nothing {
            get {
                return ResourceManager.GetString("KeyBinding_Utilities_CursorBehaviour_Nothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle through dialog options.
        /// </summary>
        public static string KeyBinding_Utilities_CycleThrough {
            get {
                return ResourceManager.GetString("KeyBinding_Utilities_CycleThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide cursor on manual selection.
        /// </summary>
        public static string KeyBinding_Utilities_HideCursorOnManualClick {
            get {
                return ResourceManager.GetString("KeyBinding_Utilities_HideCursorOnManualClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric action behavior.
        /// </summary>
        public static string KeyBinding_Utilities_NumericActionBehaviour {
            get {
                return ResourceManager.GetString("KeyBinding_Utilities_NumericActionBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlights.
        /// </summary>
        public static string KeyBinding_Utilities_NumericActionBehaviour_Highlight {
            get {
                return ResourceManager.GetString("KeyBinding_Utilities_NumericActionBehaviour_Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects.
        /// </summary>
        public static string KeyBinding_Utilities_NumericActionBehaviour_Select {
            get {
                return ResourceManager.GetString("KeyBinding_Utilities_NumericActionBehaviour_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single dialog option behavior.
        /// </summary>
        public static string KeyBinding_Utilities_SingleDialogOptionBehaviour {
            get {
                return ResourceManager.GetString("KeyBinding_Utilities_SingleDialogOptionBehaviour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any action highlights.
        /// </summary>
        public static string KeyBinding_Utilities_SingleDialogOptionBehaviour_Highlight {
            get {
                return ResourceManager.GetString("KeyBinding_Utilities_SingleDialogOptionBehaviour_Highlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any action selects.
        /// </summary>
        public static string KeyBinding_Utilities_SingleDialogOptionBehaviour_Select {
            get {
                return ResourceManager.GetString("KeyBinding_Utilities_SingleDialogOptionBehaviour_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string Language_Automatic {
            get {
                return ResourceManager.GetString("Language_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string Language_Name {
            get {
                return ResourceManager.GetString("Language_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        public static string Menu_Appearance {
            get {
                return ResourceManager.GetString("Menu_Appearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debugging.
        /// </summary>
        public static string Menu_DebugMode {
            get {
                return ResourceManager.GetString("Menu_DebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hook controls.
        /// </summary>
        public static string Menu_HookControl {
            get {
                return ResourceManager.GetString("Menu_HookControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key bindings.
        /// </summary>
        public static string Menu_KeyBindings {
            get {
                return ResourceManager.GetString("Menu_KeyBindings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-release.
        /// </summary>
        public static string Menu_PreRelease {
            get {
                return ResourceManager.GetString("Menu_PreRelease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presets.
        /// </summary>
        public static string Menu_Presets {
            get {
                return ResourceManager.GetString("Menu_Presets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Menu_Version {
            get {
                return ResourceManager.GetString("Menu_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add game extensions and restart the application.
        /// </summary>
        public static string MissingExtensions_Description {
            get {
                return ResourceManager.GetString("MissingExtensions_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extensions are missing.
        /// </summary>
        public static string MissingExtensions_Title {
            get {
                return ResourceManager.GetString("MissingExtensions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string NotifyMenu_Exit {
            get {
                return ResourceManager.GetString("NotifyMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string NotifyMenu_Open {
            get {
                return ResourceManager.GetString("NotifyMenu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshots.
        /// </summary>
        public static string NotifyMenu_Screenshots {
            get {
                return ResourceManager.GetString("NotifyMenu_Screenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application folder.
        /// </summary>
        public static string Settings_ApplicationFolder {
            get {
                return ResourceManager.GetString("Settings_ApplicationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close minimizes.
        /// </summary>
        public static string Settings_CloseMinimizes {
            get {
                return ResourceManager.GetString("Settings_CloseMinimizes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced features.
        /// </summary>
        public static string Settings_ExpertMode_Description {
            get {
                return ResourceManager.GetString("Settings_ExpertMode_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expert mode.
        /// </summary>
        public static string Settings_ExpertMode_Title {
            get {
                return ResourceManager.GetString("Settings_ExpertMode_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string Settings_General {
            get {
                return ResourceManager.GetString("Settings_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet.
        /// </summary>
        public static string Settings_Internet {
            get {
                return ResourceManager.GetString("Settings_Internet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Settings_Language {
            get {
                return ResourceManager.GetString("Settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimize to taskbar.
        /// </summary>
        public static string Settings_MinimizeToTaskBar {
            get {
                return ResourceManager.GetString("Settings_MinimizeToTaskBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When a screenshot is taken, play a sound.
        /// </summary>
        public static string Settings_Screenshots_SoundPlayback_Title {
            get {
                return ResourceManager.GetString("Settings_Screenshots_SoundPlayback_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Will open only if screenshots have been taken.
        /// </summary>
        public static string Settings_ScreenshotsManager_Description {
            get {
                return ResourceManager.GetString("Settings_ScreenshotsManager_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open screenshots folder on game exit.
        /// </summary>
        public static string Settings_ScreenshotsManager_Title {
            get {
                return ResourceManager.GetString("Settings_ScreenshotsManager_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings folder.
        /// </summary>
        public static string Settings_SettingsFolder {
            get {
                return ResourceManager.GetString("Settings_SettingsFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start minimized.
        /// </summary>
        public static string Settings_StartMinimized {
            get {
                return ResourceManager.GetString("Settings_StartMinimized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run on Windows start-up.
        /// </summary>
        public static string Settings_Startup {
            get {
                return ResourceManager.GetString("Settings_Startup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete startup setting.
        /// </summary>
        public static string Settings_Startup_Exception_Delete {
            get {
                return ResourceManager.GetString("Settings_Startup_Exception_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create startup setting.
        /// </summary>
        public static string Settings_Startup_Exception_Save {
            get {
                return ResourceManager.GetString("Settings_Startup_Exception_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unload UI when minimized to save memory.
        /// </summary>
        public static string Settings_UnloadUi_Description {
            get {
                return ResourceManager.GetString("Settings_UnloadUi_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unload UI.
        /// </summary>
        public static string Settings_UnloadUi_Title {
            get {
                return ResourceManager.GetString("Settings_UnloadUi_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update server.
        /// </summary>
        public static string Settings_Update_AppServer {
            get {
                return ResourceManager.GetString("Settings_Update_AppServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default user agent.
        /// </summary>
        public static string Settings_UserAgent {
            get {
                return ResourceManager.GetString("Settings_UserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Utilities.
        /// </summary>
        public static string Settings_Utils {
            get {
                return ResourceManager.GetString("Settings_Utils", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string Settings_WindowsState_Default {
            get {
                return ResourceManager.GetString("Settings_WindowsState_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window state on startup.
        /// </summary>
        public static string Settings_WindowsState_Main_Title {
            get {
                return ResourceManager.GetString("Settings_WindowsState_Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Window state on shortcut startup.
        /// </summary>
        public static string Settings_WindowsState_Shortcut_Title {
            get {
                return ResourceManager.GetString("Settings_WindowsState_Shortcut_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System tray.
        /// </summary>
        public static string Settings_WindowsState_SystemTray {
            get {
                return ResourceManager.GetString("Settings_WindowsState_SystemTray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task bar.
        /// </summary>
        public static string Settings_WindowsState_TaskBar {
            get {
                return ResourceManager.GetString("Settings_WindowsState_TaskBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string TextInputDialog_Apply {
            get {
                return ResourceManager.GetString("TextInputDialog_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TextInputDialog_Cancel {
            get {
                return ResourceManager.GetString("TextInputDialog_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string TextInputDialog_Reset {
            get {
                return ResourceManager.GetString("TextInputDialog_Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing.
        /// </summary>
        public static string TextInputDialog_Title {
            get {
                return ResourceManager.GetString("TextInputDialog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new.
        /// </summary>
        public static string TriggerEditor_AddNew {
            get {
                return ResourceManager.GetString("TriggerEditor_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string TriggerEditor_Apply {
            get {
                return ResourceManager.GetString("TriggerEditor_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string TriggerEditor_Cancel {
            get {
                return ResourceManager.GetString("TriggerEditor_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string TriggerEditor_Delete {
            get {
                return ResourceManager.GetString("TriggerEditor_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string TriggerEditor_Edit {
            get {
                return ResourceManager.GetString("TriggerEditor_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s nothing here yet.
        /// </summary>
        public static string TriggerEditor_EmptyTriggers {
            get {
                return ResourceManager.GetString("TriggerEditor_EmptyTriggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string TriggerEditor_MoveDown {
            get {
                return ResourceManager.GetString("TriggerEditor_MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string TriggerEditor_MoveUp {
            get {
                return ResourceManager.GetString("TriggerEditor_MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to assign it to this action, or press.
        /// </summary>
        public static string TriggerEditor_RecordingMessage_Part1 {
            get {
                return ResourceManager.GetString("TriggerEditor_RecordingMessage_Part1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to cancel.
        /// </summary>
        public static string TriggerEditor_RecordingMessage_Part2 {
            get {
                return ResourceManager.GetString("TriggerEditor_RecordingMessage_Part2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trigger editor.
        /// </summary>
        public static string TriggerEditor_Title {
            get {
                return ResourceManager.GetString("TriggerEditor_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Triggers.
        /// </summary>
        public static string TriggerEditor_Triggers {
            get {
                return ResourceManager.GetString("TriggerEditor_Triggers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client size.
        /// </summary>
        public static string WindowInfo_ClientSize {
            get {
                return ResourceManager.GetString("WindowInfo_ClientSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimized.
        /// </summary>
        public static string WindowInfo_Minimized {
            get {
                return ResourceManager.GetString("WindowInfo_Minimized", resourceCulture);
            }
        }
    }
}
