//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WhyOrchid.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#2cb065")]
        public string Color_Primary {
            get {
                return ((string)(this["Color_Primary"]));
            }
            set {
                this["Color_Primary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#f0f0f0")]
        public string Color_OnPrimary {
            get {
                return ((string)(this["Color_OnPrimary"]));
            }
            set {
                this["Color_OnPrimary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ffffff")]
        public string Color_Secondary {
            get {
                return ((string)(this["Color_Secondary"]));
            }
            set {
                this["Color_Secondary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string Color_OnSecondary {
            get {
                return ((string)(this["Color_OnSecondary"]));
            }
            set {
                this["Color_OnSecondary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#645a72")]
        public string Color_Tertiary {
            get {
                return ((string)(this["Color_Tertiary"]));
            }
            set {
                this["Color_Tertiary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ffffff")]
        public string Color_OnTertiary {
            get {
                return ((string)(this["Color_OnTertiary"]));
            }
            set {
                this["Color_OnTertiary"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#b23535")]
        public string Color_Error {
            get {
                return ((string)(this["Color_Error"]));
            }
            set {
                this["Color_Error"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ffffff")]
        public string Color_OnError {
            get {
                return ((string)(this["Color_OnError"]));
            }
            set {
                this["Color_OnError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#f5f5f5")]
        public string Color_Background {
            get {
                return ((string)(this["Color_Background"]));
            }
            set {
                this["Color_Background"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#505050")]
        public string Color_OnBackground {
            get {
                return ((string)(this["Color_OnBackground"]));
            }
            set {
                this["Color_OnBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string Color_InverseBackground {
            get {
                return ((string)(this["Color_InverseBackground"]));
            }
            set {
                this["Color_InverseBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ffffff")]
        public string Color_OnInverseBackground {
            get {
                return ((string)(this["Color_OnInverseBackground"]));
            }
            set {
                this["Color_OnInverseBackground"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#fbfbfb")]
        public string Color_Surface {
            get {
                return ((string)(this["Color_Surface"]));
            }
            set {
                this["Color_Surface"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#505050")]
        public string Color_OnSurface {
            get {
                return ((string)(this["Color_OnSurface"]));
            }
            set {
                this["Color_OnSurface"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string Color_InverseSurface {
            get {
                return ((string)(this["Color_InverseSurface"]));
            }
            set {
                this["Color_InverseSurface"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ffffff")]
        public string Color_OnInverseSurface {
            get {
                return ((string)(this["Color_OnInverseSurface"]));
            }
            set {
                this["Color_OnInverseSurface"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ffffff")]
        public string Color_SurfaceVariant {
            get {
                return ((string)(this["Color_SurfaceVariant"]));
            }
            set {
                this["Color_SurfaceVariant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#bf414141")]
        public string Color_OnSurfaceVariant {
            get {
                return ((string)(this["Color_OnSurfaceVariant"]));
            }
            set {
                this["Color_OnSurfaceVariant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string Color_InverseSurfaceVariant {
            get {
                return ((string)(this["Color_InverseSurfaceVariant"]));
            }
            set {
                this["Color_InverseSurfaceVariant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#ffffff")]
        public string Color_OnInverseSurfaceVariant {
            get {
                return ((string)(this["Color_OnInverseSurfaceVariant"]));
            }
            set {
                this["Color_OnInverseSurfaceVariant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#dcdcdc")]
        public string Color_Outline {
            get {
                return ((string)(this["Color_Outline"]));
            }
            set {
                this["Color_Outline"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#dcdcdc")]
        public string Color_OutlineVariant {
            get {
                return ((string)(this["Color_OutlineVariant"]));
            }
            set {
                this["Color_OutlineVariant"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#14383838")]
        public string Color_Interaction {
            get {
                return ((string)(this["Color_Interaction"]));
            }
            set {
                this["Color_Interaction"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#000000")]
        public string Color_Shadow {
            get {
                return ((string)(this["Color_Shadow"]));
            }
            set {
                this["Color_Shadow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double UI_ButtonCornerRadius {
            get {
                return ((double)(this["UI_ButtonCornerRadius"]));
            }
            set {
                this["UI_ButtonCornerRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double UI_CardCornerRadius {
            get {
                return ((double)(this["UI_CardCornerRadius"]));
            }
            set {
                this["UI_CardCornerRadius"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Hand")]
        public string UI_CursorType {
            get {
                return ((string)(this["UI_CursorType"]));
            }
            set {
                this["UI_CursorType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI")]
        public string FontStyle_FontFamily {
            get {
                return ((string)(this["FontStyle_FontFamily"]));
            }
            set {
                this["FontStyle_FontFamily"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("16")]
        public double FontStyle_Large {
            get {
                return ((double)(this["FontStyle_Large"]));
            }
            set {
                this["FontStyle_Large"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("14")]
        public double FontStyle_Medium {
            get {
                return ((double)(this["FontStyle_Medium"]));
            }
            set {
                this["FontStyle_Medium"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public double FontStyle_Small {
            get {
                return ((double)(this["FontStyle_Small"]));
            }
            set {
                this["FontStyle_Small"] = value;
            }
        }
    }
}
